### ISSUE TITLE
Taskforce not launching - Unexpected token = in JSON at position 1

### ISSUE THREAD

**Issue by markBerlin** [taskforcesh/issues#29]
When I try to launch taskforce with 
```
taskforce -n "My team" -t "TOKEN"
```
I get the error message

```
undefined:1
{=true
 ^

SyntaxError: Unexpected token = in JSON at position 1
    at JSON.parse (<anonymous>)
    at exports.parse (/usr/local/lib/node_modules/taskforce-connector/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/usr/local/lib/node_modules/taskforce-connector/node_modules/rc/index.js:30:20)
    at Array.forEach (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/taskforce-connector/node_modules/rc/index.js:43:36)
    at module.exports (/usr/local/lib/node_modules/taskforce-connector/node_modules/registry-url/index.js:3:24)
    at module.exports (/usr/local/lib/node_modules/taskforce-connector/node_modules/package-json/index.js:10:17)
    at module.exports (/usr/local/lib/node_modules/taskforce-connector/node_modules/latest-version/index.js:4:37)
    at Object.<anonymous> (/usr/local/lib/node_modules/taskforce-connector/index.js:55:1)
```

I tried yarn and npm, including cleaning/removing cache. 

Could it have something to do with my local npm profile?

I am working on Mac 10.15, Node  10.16.3, yarn 1.19.1.

**Comment by manast** [comment]
could you provide the complete output of the taskforce command? I verified and it works just fine in Mac and using node version 10.16.3.

**Comment by markBerlin** [comment]
Thanks for looking into it. This is the command and its output:

```
taskforce -t xxxxxxxx
Taskforce Connector v1.4.2 - (c) 2017-2019 Taskforce.sh Inc.
undefined:1
{=true
 ^

SyntaxError: Unexpected token = in JSON at position 1
    at JSON.parse (<anonymous>)
    at exports.parse (/Users/xxx/.config/yarn/global/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/Users/xxx/.config/yarn/global/node_modules/rc/index.js:30:20)
    at Array.forEach (<anonymous>)
    at module.exports (/Users/xxx/.config/yarn/global/node_modules/rc/index.js:43:36)
    at module.exports (/Users/xxx/.config/yarn/global/node_modules/registry-url/index.js:3:24)
    at module.exports (/Users/xxx/.config/yarn/global/node_modules/package-json/index.js:10:17)
    at module.exports (/Users/xxx/.config/yarn/global/node_modules/latest-version/index.js:4:37)
    at Object.<anonymous> (/Users/xxx/.config/yarn/global/node_modules/taskforce-connector/index.js:55:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

**Comment by manast** [comment]
Ok, so the error seems to be related to a third party dependency *latest-version*, I have upgraded to the latest version and made a new release 1.4.3, would you mind to test to see if it resolves your issue?

**Comment by manast** [comment]
closing due to lack of feedback.
