### ISSUE TITLE
How do I update connection username and password?

### ISSUE THREAD

**Issue by remarkablemark** [taskforcesh/issues#92]
I recently had to rotate Redis credentials and I tried to edit the connection but I am unable to do so:

![Screen Shot 2022-05-19 at 2 42 37 PM](https://user-images.githubusercontent.com/10594555/169376649-b7115db0-3d18-4d9a-ab66-707bacc66b12.png)

This is how the UI looks after I refreshed the page and clicked the edit icon:

![Screen Shot 2022-05-19 at 2 49 40 PM](https://user-images.githubusercontent.com/10594555/169377921-657f97c2-7875-4356-9e92-b16df1a35c0c.png)

I am on the desktop browser:

Google Chrome | 101.0.4951.54 (Official Build) (x86_64)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | macOS Version 11.5.2 (Build 20G95)

**Comment by manast** [comment]
@remarkablemark could you please also open the chrome dev console and take a screenshot if there is any error there please?

**Comment by remarkablemark** [comment]
Sure thing, here's the error:

![Screen Shot 2022-05-19 at 9 14 17 PM](https://user-images.githubusercontent.com/10594555/169429086-2bb4c543-00e3-4857-aeaf-43d9f2a33ce6.png)

```
ERROR TypeError: (e.monitors || []).find is not a function
    at main-es2015.a79b88b719e146c90cfd.js:1:3070277
    at Array.map (<anonymous>)
    at new e (main-es2015.a79b88b719e146c90cfd.js:1:3070253)
    at Mn.e.ɵfac [as factory] (main-es2015.a79b88b719e146c90cfd.js:1:3071406)
    at Xn (main-es2015.a79b88b719e146c90cfd.js:1:1283450)
    at main-es2015.a79b88b719e146c90cfd.js:1:1340667
    at sl (main-es2015.a79b88b719e146c90cfd.js:1:1340732)
    at Um.create (main-es2015.a79b88b719e146c90cfd.js:1:1409986)
    at po.createComponent (main-es2015.a79b88b719e146c90cfd.js:1:1316224)
    at e.attachComponentPortal (main-es2015.a79b88b719e146c90cfd.js:1:1998230)
```

```
ERROR TypeError: Cannot read properties of undefined (reading 'focusInitialElementWhenReady')
    at e._trapFocus (main-es2015.a79b88b719e146c90cfd.js:1:2041789)
    at e._onAnimationDone (main-es2015.a79b88b719e146c90cfd.js:1:2043459)
    at main-es2015.a79b88b719e146c90cfd.js:1:2044332
    at fc (main-es2015.a79b88b719e146c90cfd.js:1:1350079)
    at r (main-es2015.a79b88b719e146c90cfd.js:1:1350239)
    at main-es2015.a79b88b719e146c90cfd.js:1:1918711
    at u.invoke (polyfills-es2015.3c2c9278a7692bb7d303.js:1:29010)
    at Object.onInvoke (main-es2015.a79b88b719e146c90cfd.js:1:1437477)
    at u.invoke (polyfills-es2015.3c2c9278a7692bb7d303.js:1:28950)
    at a.run (polyfills-es2015.3c2c9278a7692bb7d303.js:1:24422)
```

**Comment by manast** [comment]
I am not really able to reproduce this issue, I wonder if it works when you delete the connection and add it again?

**Comment by remarkablemark** [comment]
Yes, deleting the connection and re-adding it works. Thanks for the tip.
